debug: true

server: 
  context-path: /rest/v1

git.service.account.token: pWtB2gbhv72TmHo7fnK1

git: 
  project.information.regex: "^.*:([\\\\w_-]*)\\\\/([\\\\w_-]*).git$"
  service.account.token: pWtB2gbhv72TmHo7fnK1
  url: "https://git.labs.nuance.com"

