debug: true

server: 
  context-path: /rest/v1

git: 
  project.information.regex: "^.*:(.*)/([\\w_-]*).git$"
  service.account.token: pWtB2gbhv72TmHo7fnK1
  url: "https://git.labs.nuance.com"


mvn:
  repo:
    protocol: http
    hostname: 10.3.41.66
    port: 8081
    url: /artifactory/repo/
    username: admin
    password: password
  
artifactory:
  dependency:
    propertyname: trigger
    propertyvalue: true

